from .category import *
from .news import *
from .contact import *
from .faq import *
from .partner import *
from .project import *
from .tovar import *
from .client import *
from .headercontacts import *
from .Card import *